theme: jekyll-theme-tactile
title: Welcome to Claire's generic homepage!
description: This is a personal project to practice HTML.

[LinkedIn](https://www.linkedin.com/in/claire-armstrong/)
[AngelList](https://angel.co/claire-armstrong-3?public_profile=1)
